services:
  server:
    image: standardnotes/server
    container_name: server_self_hosted
    restart: unless-stopped
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USERNAME=std_notes_user
      - DB_PASSWORD=$DB_PASSWORD
      - DB_DATABASE=standard_notes_db
      - DB_TYPE=mysql
      - REDIS_PORT=6379
      - REDIS_HOST=cache
      - CACHE_TYPE=redis
      - PUBLIC_FILES_SERVER_URL=$PUBLIC_FILES_SERVER_URL
      - AUTH_JWT_SECRET=$AUTH_JWT_SECRET
      - AUTH_SERVER_ENCRYPTION_SERVER_KEY=$AUTH_SERVER_ENCRYPTION_SERVER_KEY
      - VALET_TOKEN_SECRET=$VALET_TOKEN_SECRET
    ports:
      - 3000:3000 # sync service
      - 3125:3104 # files service
    volumes:
      - $INSTALL_DIR/logs:/var/lib/server/logs
      - $INSTALL_DIR/uploads:/opt/server/packages/files/dist/uploads
    networks:
      - standardnotes_self_hosted
      - gateway

  web:
    image: standardnotes/web
    container_name: web_self_hosted
    restart: unless-stopped
    #ports:
    #  - 3001:80
    networks:
      - standardnotes_self_hosted
      - gateway

  localstack:
    image: localstack/localstack:3.0
    container_name: localstack_self_hosted
    expose:
      - 4566
    restart: unless-stopped
    environment:
      - SERVICES=sns,sqs
      - HOSTNAME_EXTERNAL=localstack
      - LS_LOG=warn
    volumes:
      - $INSTALL_DIR/localstack_bootstrap.sh:/etc/localstack/init/ready.d/localstack_bootstrap.sh
    networks:
      - standardnotes_self_hosted

  db:
    image: mysql:8
    container_name: db_self_hosted
    environment:
      - MYSQL_DATABASE=standard_notes_db
      - MYSQL_USER=std_notes_user
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_PASSWORD=$DB_PASSWORD
    expose:
      - 3306
    restart: unless-stopped
    volumes:
      - $INSTALL_DIR/data/mysql:/var/lib/mysql
      - $INSTALL_DIR/data/import:/docker-entrypoint-initdb.d
    networks:
      - standardnotes_self_hosted

  cache:
    image: redis:6.0-alpine
    container_name: cache_self_hosted
    volumes:
      - $INSTALL_DIR/data/redis/:/data
    expose:
      - 6379
    restart: unless-stopped
    networks:
      - standardnotes_self_hosted

networks:
  standardnotes_self_hosted:
    name: standardnotes_self_hosted
  gateway:
    external: true
    name: gateway
