networks:
  linkwarden:
    name: linkwarden
  gateway:
    external: true
    name: gateway

services:
  postgres:
    image: postgres:16-alpine
    restart: unless_stopped
    volumes:
      - $INSTALL_DIR/db:/var/lib/postgresql/data
    networks:
      - linkwarden
  linkwarden:
    environment:
      - NEXTAUTH_URL=$NEXTAUTH_URL
      - NEXTAUTH_SECRET=$NEXTAUTH_SECRET
      - NEXT_PUBLIC_AUTHENTIK_ENABLED=true
      - AUTHENTIK_CUSTOM_NAME=
      - AUTHENTIK_ISSUER=$AUTHENTIK_ISSUER
      - AUTHENTIK_CLIENT_ID=$AUTHENTIK_CLIENT_ID
      - AUTHENTIK_CLIENT_SECRET=$AUTHENTIK_CLIENT_SECRET
      - DATABASE_URL=$DATABASE_URL
    restart: unless_stopped
    image: ghcr.io/linkwarden/linkwarden:latest
    volumes:
      - $INSTALL_DIR/app:/data/data
    depends_on:
      - postgres
    networks:
      - gateway
      - linkwarden
