version: '3.8'

networks:
  gateway:
    external: true
    name: gateway

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    #ports:
    #  - "8081:8081"
    #  - "8082:8082"
    volumes:
      - $INSTALL_DIR:/var/opt/jfrog/artifactory
    user: "1030:1030"
    networks:
      - gateway
    environment:
      - EXTRA_JAVA_OPTIONS=-Xms512m -Xmx2g
    restart: unless-stopped
